[package]
name = "serde_nbt"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
rnbt = { git = "https://github.com/awegsche/rnbt.git", version = "0.1.0" }
serde = {version = "1.0.216", features = ["derive"]}
