[package]
name = "serde_nbt"
version = "0.1.0"
edition = "2024"

[dependencies]
rnbt = { git = "https://github.com/awegsche/rnbt.git", version = "0.1.0" }
serde = {version = "1.0.216", features = ["derive"]}
